"use strict";

const { stripHostPort } = require("./naming");

function caddyHost(host) {
  const normalized = stripHostPort(host);
  if (!/^(\*\.)?[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)*$/.test(normalized)) {
    throw new Error(`Unsafe Caddy host: ${host}`);
  }
  return normalized;
}

function caddyUpstream(targetUrl) {
  const parsed = new URL(String(targetUrl || ""));
  if (!["http:", "https:"].includes(parsed.protocol)) {
    throw new Error(`Unsupported route target protocol: ${targetUrl}`);
  }
  if ((parsed.pathname && parsed.pathname !== "/") || parsed.search || parsed.hash) {
    throw new Error(`Route target must be an origin without path/query/hash: ${targetUrl}`);
  }
  return parsed.origin;
}

function caddyEmail(email) {
  const value = String(email || "").trim();
  if (!value) return "";
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
    throw new Error(`Unsafe Caddy email: ${email}`);
  }
  return value;
}

function generateCaddyfile(routes, options = {}) {
  const activeRoutes = routes
    .filter((route) => route.active !== false)
    .map((route) => ({
      ...route,
      host: caddyHost(route.host),
      targetUrl: caddyUpstream(route.targetUrl)
    }))
    .sort((left, right) => left.host.localeCompare(right.host));

  const lines = [
    "# Generated by: a1 gateway caddy",
    "# Source: A1 Platform tenant_routes",
    "# Do not edit generated tenant blocks by hand.",
    ""
  ];

  const email = caddyEmail(options.email);
  if (email) {
    lines.push("{", `  email ${email}`, "}", "");
  }

  if (!activeRoutes.length) {
    lines.push("# No active tenant routes found.", "");
    return `${lines.join("\n")}\n`;
  }

  for (const route of activeRoutes) {
    lines.push(
      `# tenant=${route.slug || "unknown"} product=${route.productCode || "unified"} target=${route.deploymentTarget || "unknown"}`,
      `${route.host} {`,
      "  encode zstd gzip",
      `  reverse_proxy ${route.targetUrl}`,
      "}",
      ""
    );
  }

  return `${lines.join("\n")}\n`;
}

module.exports = {
  caddyEmail,
  caddyHost,
  caddyUpstream,
  generateCaddyfile
};
